// avatars.ts — bundled avatar set helpers. Numbered 1..AVATAR_COUNT;
// the SVGs themselves live at `apps/web/public/avatars/<id>.svg` and
// are generated by `scripts/gen-avatars.mjs`.

export const AVATAR_COUNT = 24
export const defaultAvatarId = '1'

export function avatarIds(): string[] {
  return Array.from({ length: AVATAR_COUNT }, (_, i) => String(i + 1))
}

export function normalizeAvatarId(raw: unknown): string | null {
  if (raw == null) return null
  const n = Number(raw)
  if (!Number.isInteger(n) || n < 1 || n > AVATAR_COUNT) return null
  return String(n)
}

export function avatarUrl(id: string | number | null | undefined): string {
  const norm = normalizeAvatarId(id) ?? defaultAvatarId
  return `/avatars/${norm}.svg`
}
